# Generated by Django 6.0 on 2025-12-21 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_url', models.URLField(max_length=2028)),
                ('short_code', models.CharField(max_length=50, unique=True)),
                ('access_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'short_urls',
                'indexes': [models.Index(fields=['short_code'], name='idx_short_code'), models.Index(fields=['created_at'], name='idx_created_at'), models.Index(fields=['expires_at'], name='idx_expires_at'), models.Index(fields=['updated_at'], name='idx_updated_at')],
            },
        ),
    ]
